name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    
    steps:
    - uses: actions/checkout@v4

#    - name: Install and update packages
#      run: |
#        apt-get -y install python3 python3-pip p7zip-full libarchive13
#        python3 --version
#        python3 -m pip install --upgrade pip setuptools
#        python3 -m pip install cryptography git+https://github.com/TuxSH/firmtool.git

    
    - name: make
      run: make

    - uses: actions/upload-artifact@v4
      with:
        name: out
        path: arm11/*
